# 1. Overview

## 1.0 Setup and Data Loading

In [15]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [16]:
neiss_2024 = pd.read_excel('../raw_data/neiss_2024_raw.xlsx')

print("Shape:", neiss_2024.shape)
display(neiss_2024.head())

Shape: (361672, 25)

,CPSC_Case_Number,Treatment_Date,Age,Sex,Race,Other_Race,Hispanic,Body_Part,Diagnosis,Other_Diagnosis,...,Fire_Involvement,Product_1,Product_2,Product_3,Alcohol,Drug,Narrative_1,Stratum,PSU,Weight
0,240108461,2024-01-01,16,1,0,NaN,1,30,64,NaN,...,0,1267,0,0,0,0,"16YOM PLAYING SOCCER, HURT HIS SHOULDER. HIT ...",S,29,104.4634
1,240108462,2024-01-01,56,2,1,NaN,2,92,59,NaN,...,0,464,0,0,0,0,56YOF WAS CUTTING UP CABBAGE AND KNIFE SLIPPED...,S,29,104.4634
2,240109863,2024-01-01,10,1,1,NaN,2,93,54,NaN,...,0,5036,1615,0,0,0,10 YOM C/O CRUSH INJURY OF TOE S/P RIDING A DI...,C,204,7.5201
3,240109864,2024-01-01,3,2,0,NaN,2,0,41,NaN,...,0,1686,0,0,0,0,3 YOF PRESENTS WITH SWALLOWED FOREIGN BODY S/P...,C,204,7.5201
4,240109865,2024-01-01,2,1,0,NaN,1,76,59,NaN,...,0,4074,0,0,0,0,2 YOM PRESENTS WITH FACIAL LACERATION S/P FELL...,C,204,7.5201

## 1.2 Checking for Detailed Information About the Data

In [17]:
neiss_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361672 entries, 0 to 361671
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CPSC_Case_Number   361672 non-null  int64
 1   Treatment_Date     361672 non-null  datetime64[ns]
 2   Age                361672 non-null  int64
 3   Sex                361672 non-null  int64
 4   Race               361672 non-null  int64
 5   Other_Race         15277 non-null   object
 6   Hispanic           361672 non-null  int64
 7   Body_Part          361672 non-null  int64
 8   Diagnosis          361672 non-null  int64
 9   Other_Diagnosis    77535 non-null   object
 10  Body_Part_2        88551 non-null   float64
 11  Diagnosis_2        88551 non-null   float64
 12  Other_Diagnosis_2  22830 non-null   object
 13  Disposition        361672 non-null  int64
 14  Location           361672 non-null  int64
 15  Fire_Involvement   361672 non-null  int64
 16  Product_1          361672 non-null  int64
 17  Product_2          361672 non-null  int64
 18  Product_3          361672 non-null  int64
 19  Alcohol            361672 non-null  int64
 20  Drug               361672 non-null  int64
 21  Narrative_1        361672 non-null  object
 22  Stratum            361672 non-null  object
 23  PSU                361672 non-null  int64
 24  Weight             361672 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(16), object(5)
memory usage: 69.0+ MB

## 1.3 Evaluating Missing Data Patterns

In [18]:
missing_summary = (
    neiss_2024.isna()
    .sum()
    .to_frame("missing_count")
)

missing_summary["missing_pct"] = (
    missing_summary["missing_count"] / len(neiss_2024) * 100
)

missing_summary.sort_values("missing_pct", ascending=False)

                   missing_count  missing_pct
Other_Race                346395    95.776007
Other_Diagnosis_2         338842    93.687651
Other_Diagnosis           284137    78.562067
Diagnosis_2               273121    75.516214
Body_Part_2               273121    75.516214
CPSC_Case_Number               0     0.000000
Treatment_Date                 0     0.000000
Sex                            0     0.000000
Age                            0     0.000000
Diagnosis                      0     0.000000
Body_Part                      0     0.000000
Hispanic                       0     0.000000
Race                           0     0.000000
Disposition                    0     0.000000
Location                       0     0.000000
Fire_Involvement               0     0.000000
Product_1                      0     0.000000
Product_2                      0     0.000000
Product_3                      0     0.000000
Alcohol                        0     0.000000
Drug                           0     0.000000
Narrative_1                    0     0.000000
Stratum                        0     0.000000
PSU                            0     0.000000
Weight                         0     0.000000

## 1.4 Descriptive Statistics for Numeric Variables

In [19]:
neiss_2024.describe()

,CPSC_Case_Number,Treatment_Date,Age,Sex,Race,Hispanic,Body_Part,Diagnosis,Body_Part_2,Diagnosis_2,Disposition,Location,Fire_Involvement,Product_1,Product_2,Product_3,Alcohol,Drug,PSU,Weight
count,3.616720e+05,361672,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000,88551.000000,88551.000000,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000,361672.000000
mean,2.412749e+08,2024-07-05 15:46:33.346457088,47.561575,1.450859,1.210887,1.575179,64.598329,61.202866,65.320821,61.394146,1.472812,2.432837,0.011248,2189.587192,312.119113,31.325386,0.018215,0.027464,53.668205,41.664765
min,2.401085e+08,2024-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,41.000000,0.000000,41.000000,1.000000,0.000000,0.000000,106.000000,0.000000,0.000000,0.000000,0.000000,2.000000,6.580100
25%,2.405001e+08,2024-04-12 00:00:00,13.000000,1.000000,1.000000,1.000000,36.000000,57.000000,35.000000,53.000000,1.000000,0.000000,0.000000,1211.000000,0.000000,0.000000,0.000000,0.000000,21.000000,27.587000
50%,2.407884e+08,2024-07-08 00:00:00,34.000000,1.000000,1.000000,2.000000,75.000000,59.000000,76.000000,59.000000,1.000000,1.000000,0.000000,1807.000000,0.000000,0.000000,0.000000,0.000000,41.000000,27.587000
75%,2.410680e+08,2024-09-30 00:00:00,67.000000,2.000000,2.000000,2.000000,82.000000,65.000000,82.000000,71.000000,1.000000,5.000000,0.000000,3285.000000,0.000000,0.000000,0.000000,0.000000,73.000000,53.129500
max,2.503063e+08,2024-12-31 00:00:00,223.000000,2.000000,6.000000,2.000000,94.000000,74.000000,94.000000,74.000000,9.000000,9.000000,3.000000,5555.000000,5555.000000,5555.000000,1.000000,1.000000,207.000000,108.065600
std,2.194381e+06,NaN,50.063627,0.499554,0.900027,0.725550,24.003102,6.746135,22.776818,7.328551,1.200245,3.288587,0.169658,1392.884748,839.127837,274.427963,0.133730,0.163432,44.858434,29.854678

## 1.5 Distribution of Categorical Variables

In [20]:
categorical_cols = neiss_2024.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n===== {col} =====")
    display(neiss_2024[col].value_counts().head(10))

===== Other_Race =====

Other_Race
UNKNOWN         8363
MULTI-RACIAL    2459
NS              1222
HISPANIC         946
MULTIRACIAL      448
MEXICAN          281
BIRACIAL         208
UNK              171
MULTI RACIAL     114
MULTI            108
Name: count, dtype: int64

===== Other_Diagnosis =====

Other_Diagnosis
PAIN              37864
INJURY             5470
NS                 3326
NO INJURY          2108
HEADACHE           1236
CELLULITIS         1158
NOT STATED          703
CHEST PAIN          564
FALL NO INJURY      552
OTITIS EXTERNA      528
Name: count, dtype: int64

===== Other_Diagnosis_2 =====

Other_Diagnosis_2
PAIN             14145
INJURY             902
CELLULITIS         754
HEADACHE           458
NS                 429
SWELLING           290
NECK PAIN          209
NO INJURY          162
SHOULDER PAIN      147
KNEE PAIN          120
Name: count, dtype: int64

===== Narrative_1 =====

Narrative_1
16YOM TWISTED ANKLE PLAYING BASKETBALL.  DX: ANKLE SPRAIN    15
17YOM TWISTED ANKLE PLAYING BASKETBALL.  DX: ANKLE SPRAIN    11
2YOM FELL DOWN STEPS.  DX: HEAD INJURY                        9
6YOM FELL OFF MONKEY BARS.  DX: RADIUS FX                     8
4YOF SWALLOWED A COIN.  DX: FB INGESTED                       8
4YOM SWALLOWED A COIN.  DX: FB INGESTED                       8
6YOM SWALLOWED A COIN.  DX: FB INGESTED                       8
2YOM SWALLOWED A COIN.  DX: FB INGESTED                       7
15YOM TWISTED ANKLE PLAYING BASKETBALL.  DX: ANKLE SPRAIN     7
2YOF WITH A BEAD IN NOSE.  DX: FB NOSE                        7
Name: count, dtype: int64

===== Stratum =====

Stratum
V    117020
C     76366
L     67836
M     55287
S     45163
Name: count, dtype: int64

## 1.6 Examining Outcome Variable Distribution

In [21]:
neiss_2024["Disposition"].value_counts()

Disposition
1    308446
4     38146
6      7669
2      4106
5      3008
8       294
9         3
Name: count, dtype: int64

## 1.7 Validating Age Variable Coding

In [22]:
print((neiss_2024["Age"] == 0).sum())

29

## 1.8 Summary of Survey Design Variables

In [23]:
neiss_2024[["Weight", "PSU"]].describe()

              Weight            PSU
count  361672.000000  361672.000000
mean       41.664765      53.668205
std        29.854678      44.858434
min         6.580100       2.000000
25%        27.587000      21.000000
50%        27.587000      41.000000
75%        53.129500      73.000000
max       108.065600     207.000000

In [24]:
neiss_2024["Stratum"].value_counts()

Stratum
V    117020
C     76366
L     67836
M     55287
S     45163
Name: count, dtype: int64